# Generated by Django 3.0.4 on 2020-04-02 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_new', models.CharField(max_length=64, verbose_name='Название')),
                ('text_new', models.CharField(max_length=256, verbose_name='Текст')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публиуации')),
                ('file_new', models.FileField(upload_to='news/image/', verbose_name='Документ')),
                ('image_new', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
