# Generated by Django 3.0.4 on 2020-04-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='file_new',
            field=models.FileField(upload_to='news/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_new',
            field=models.ImageField(blank=True, null=True, upload_to='news/image/', verbose_name='Изображение'),
        ),
    ]
