# Generated by Django 3.0.4 on 2020-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200402_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='file_new',
            field=models.FileField(max_length=5000, upload_to='news/', verbose_name='Документ'),
        ),
    ]
