# Generated by Django 3.0.4 on 2020-04-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200402_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='text_new',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='title_new',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='new',
            name='file_new',
        ),
        migrations.RemoveField(
            model_name='new',
            name='image_new',
        ),
        migrations.AddField(
            model_name='new',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background/', verbose_name='Фон'),
        ),
        migrations.AddField(
            model_name='new',
            name='file',
            field=models.FileField(default='', upload_to='news/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(default='', upload_to='news/image/'),
            preserve_default=False,
        ),
    ]
