# Generated by Django 3.0.4 on 2020-04-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200418_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='fax',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Факс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='tel',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
