# Generated by Django 3.0.4 on 2020-04-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20200418_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(default='info@nnte.ru', max_length=20, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
