# Generated by Django 3.0.4 on 2020-04-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_about_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='important',
            field=models.TextField(default='', max_length=3000, unique=True, verbose_name='О компании'),
        ),
    ]
