# Generated by Django 3.0.4 on 2020-04-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20200409_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='article/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='new',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='news/', verbose_name='Документ'),
        ),
    ]
