# Generated by Django 3.0.4 on 2020-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_company_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, unique=True, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=500, unique=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(max_length=100000, verbose_name='Текст'),
        ),
    ]
