# Generated by Django 3.0.4 on 2020-04-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='teplo', max_length=30),
            preserve_default=False,
        ),
    ]
