# Generated by Django 3.0.4 on 2020-04-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_section_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sequence',
            field=models.SmallIntegerField(verbose_name='Порядок следования'),
        ),
    ]
