# Generated by Django 3.0.4 on 2020-04-10 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20200410_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=500000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.Section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.CharField(max_length=500000, verbose_name='Текст'),
        ),
    ]
