# Generated by Django 3.0.4 on 2020-04-22 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20200422_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=20, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='apps.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='apps.Section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='apps.Company', verbose_name='Компания'),
        ),
    ]
