# Generated by Django 3.0.4 on 2020-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20200422_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='Порядок следования'),
            preserve_default=False,
        ),
    ]
