# Generated by Django 3.0.4 on 2020-04-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_category_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимый'),
        ),
        migrations.AddField(
            model_name='section',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимый'),
        ),
    ]
