# Generated by Django 3.0.4 on 2020-04-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_auto_20200422_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sequence',
            field=models.IntegerField(default=0, unique=True, verbose_name='Порядок следования'),
            preserve_default=False,
        ),
    ]
