# Generated by Django 3.0.4 on 2020-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_department_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.CharField(max_length=20, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='department',
            name='fax',
            field=models.CharField(max_length=20, verbose_name='Факс'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
