# Generated by Django 3.0.4 on 2020-04-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20200425_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
